name: Build and deploy
on: [ push ]

jobs:
  build:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    permissions:
      checks: "write"
      contents: "read"
      id-token: "write"
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2.7.0
        with:
          arguments: --configuration-cache build installDist
